### ISSUE TITLE
Annotations on "top-level" public members can break scaladoc 3

### ISSUE THREAD

**Issue by armanbilge** [typelevel/scalac-compat#56]
Just to track this. If it's not deemed a Scala 3 issue (and I'm not sure if it would be) then we may need to rethink our implementation.

Bug (?):
- https://github.com/lampepfl/dotty/issues/18487

Workaround:
- https://github.com/typelevel/fs2/pull/3291

**Comment by satorg** [comment]
@armanbilge , can the lampepfl/dotty#18487 issue be worked around by adding `scalac-compat-annotation` directly to the `doc` task (which otherwise failing) as a regular `Compile` dependency?

**Comment by armanbilge** [comment]
Not sure, but the issue is that we shouldn't require downstream, non-sbt-typelevel users to have to modify their build in these ways just so they can use our libraries.

**Comment by armanbilge** [comment]
For now, the fix is to treat `scalac-compat-annotation` as a `Provided` library.

- https://github.com/typelevel/sbt-typelevel/issues/655
